"""recovery_package.py — off-VPS encrypted recovery/continuity package builder.

Contract: NIZAM__system/governor, T1 secret-tier custodian role per
nizamfinancialapp/ops/secrets/ALIAS_REGISTRY.md, and the "backup +
drive-connector: age-encrypt -> Drive (drive.file)" convention already named
in nizamfinancialapp/docs/NIZAM_TWO_AGENT_VPS_ARCHITECTURE.md.
Phase: G8 off-VPS recovery layer. Owner-authorized 2026-09-02. Owner supplied
an age PUBLIC key over chat; the matching PRIVATE key was generated by the
owner on their own machine and has never been seen by this process, this
repo, this VPS, or Google Drive.

Two-layer package:

  1. Plaintext manifest layer (safe to read by anyone with Drive access):
     repo commit state, service/env-file inventory (variable NAMES only,
     never values), governance-file hashes, restore instructions. No secret
     value, hostname, IP, or deployment particular is ever placed here.

  2. age-encrypted secrets layer: the actual contents of the T1 `.env`
     files under /etc/nizam/, encrypted in-process to AGE_RECOVERY_PUBLIC_KEY
     via the `age` CLI. Plaintext secret bytes exist only in this process's
     memory for the duration of one function call; they are never written
     to disk unencrypted and never logged.

This module never generates, stores, requests, or transmits an age PRIVATE
key. Decryption of the secrets layer happens off this VPS, by the owner,
with a key this code has never had access to.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import datetime
from pathlib import Path
from typing import Iterable

DEFAULT_BACKUP_ENV = Path("/etc/nizam/backup.env")
AGE_RECIPIENT_VAR = "AGE_RECOVERY_PUBLIC_KEY"


class RecoveryPackageError(RuntimeError):
    """Raised for any recovery-package build/encrypt failure."""


def get_age_recipient(backup_env_path: Path = DEFAULT_BACKUP_ENV) -> str:
    """Read the age recipient (PUBLIC key only) out of the T1 backup.env.

    Raises RecoveryPackageError if the file or the variable is missing.
    Never reads or returns anything resembling a private key: this looks
    for exactly one `KEY=value` line and returns the value verbatim.
    """
    if not backup_env_path.exists():
        raise RecoveryPackageError(f"backup env file not found: {backup_env_path}")
    for line in backup_env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key.strip() == AGE_RECIPIENT_VAR:
            value = value.strip().strip('"').strip("'")
            if not value:
                raise RecoveryPackageError(f"{AGE_RECIPIENT_VAR} is set but empty")
            return value
    raise RecoveryPackageError(f"{AGE_RECIPIENT_VAR} not found in {backup_env_path}")


def encrypt_bytes(plaintext: bytes, recipient: str, age_bin: str = "age") -> bytes:
    """age-encrypt `plaintext` to `recipient` (a public key). Never touches disk.

    Runs `age -r <recipient>` with plaintext piped via stdin and ciphertext
    captured from stdout. Raises RecoveryPackageError on any non-zero exit.
    """
    if not recipient.startswith("age1"):
        raise RecoveryPackageError(
            f"recipient does not look like an age public key: {recipient[:8]}..."
        )
    proc = subprocess.run(
        [age_bin, "-r", recipient],
        input=plaintext,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RecoveryPackageError(
            f"age encryption failed (exit {proc.returncode}): "
            f"{proc.stderr.decode('utf-8', errors='replace')}"
        )
    if not proc.stdout:
        raise RecoveryPackageError("age produced empty ciphertext")
    return proc.stdout


def decrypt_bytes(ciphertext: bytes, identity_file: Path, age_bin: str = "age") -> bytes:
    """age-decrypt `ciphertext` using a private-key identity file.

    Only ever called in tests, against a throwaway synthetic keypair
    generated for the test itself. This function is never called against
    the owner's real key by this codebase: the owner decrypts off-VPS,
    outside this repo's execution.
    """
    proc = subprocess.run(
        [age_bin, "-d", "-i", str(identity_file)],
        input=ciphertext,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RecoveryPackageError(
            f"age decryption failed (exit {proc.returncode}): "
            f"{proc.stderr.decode('utf-8', errors='replace')}"
        )
    return proc.stdout


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def env_var_names(content: str) -> list[str]:
    """Extract variable NAMES (never values) from a KEY=value env file body."""
    names = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, _ = line.partition("=")
        key = key.strip()
        if key:
            names.append(key)
    return names


def build_manifest(
    env_file_names: Iterable[str],
    env_file_var_names: dict[str, list[str]],
    governance_hashes: dict[str, str],
    repo_commits: dict[str, str],
    kill_switch_file_present: bool,
    generated_at: str | None = None,
) -> dict:
    """Assemble the plaintext (non-secret) manifest layer.

    Every input here is metadata: file names, variable NAMES, hex hashes,
    short commit ids, and a boolean. No secret value, hostname, IP, or
    credential ever enters this structure — callers must not pass one in.
    """
    return {
        "schema": "nizam-recovery-manifest/v1",
        "generated_at": generated_at or datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "secret_tier_env_files": sorted(env_file_names),
        "env_file_variable_names": {k: sorted(v) for k, v in env_file_var_names.items()},
        "governance_file_hashes": governance_hashes,
        "repo_commits": repo_commits,
        "kill_switch_file_present": kill_switch_file_present,
        "notes": [
            "This manifest contains no secret values. Variable names only.",
            "The accompanying secrets.age file is age-encrypted to the owner's "
            "recovery public key; only the owner's offline private key can "
            "decrypt it. This process never held that private key.",
        ],
    }


def collect_secret_bundle(file_contents: dict[str, bytes]) -> bytes:
    """Concatenate multiple secret-file contents into one labeled bundle.

    Pure function: takes already-read bytes (dict of filename -> content),
    does no filesystem or privilege-escalation work itself, so it is fully
    unit-testable with synthetic data. The privileged read of the real
    /etc/nizam/*.env files happens in a separate, thin, untested caller.
    """
    parts = []
    for name in sorted(file_contents):
        header = f"# === {name} ===\n".encode("utf-8")
        body = file_contents[name]
        if not body.endswith(b"\n"):
            body = body + b"\n"
        parts.append(header + body)
    return b"\n".join(parts)


def write_package(
    output_dir: Path,
    manifest: dict,
    encrypted_secrets: bytes,
    restore_instructions_md: str,
) -> dict[str, str]:
    """Write the four package files to output_dir and return their sha256 hashes.

    Files written: MANIFEST.json (plaintext), secrets.age (ciphertext only),
    RESTORE_INSTRUCTIONS.md (plaintext), HASHES.json (sha256 of the other
    three, so any bit-flip in transit or at rest is detectable).
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    restore_bytes = restore_instructions_md.encode("utf-8")

    manifest_path = output_dir / "MANIFEST.json"
    secrets_path = output_dir / "secrets.age"
    restore_path = output_dir / "RESTORE_INSTRUCTIONS.md"
    hashes_path = output_dir / "HASHES.json"

    manifest_path.write_bytes(manifest_bytes)
    secrets_path.write_bytes(encrypted_secrets)
    restore_path.write_bytes(restore_bytes)

    hashes = {
        "MANIFEST.json": sha256_hex(manifest_bytes),
        "secrets.age": sha256_hex(encrypted_secrets),
        "RESTORE_INSTRUCTIONS.md": sha256_hex(restore_bytes),
    }
    hashes_path.write_bytes((json.dumps(hashes, indent=2, sort_keys=True) + "\n").encode("utf-8"))
    return hashes


RESTORE_INSTRUCTIONS_TEMPLATE = """# NIZAM Off-VPS Recovery — Restore Instructions

Generated: {generated_at}

## What this package is

A point-in-time recovery snapshot of NIZAM's non-secret continuity state
(this MANIFEST.json + HASHES.json) plus one age-encrypted bundle
(secrets.age) containing the real contents of every T1 `.env` file that was
live on the VPS at capture time.

## What you need to decrypt it

Your age PRIVATE key — the file you generated locally with `age-keygen` and
stored off both the VPS and Google Drive (password manager, encrypted USB,
or similar). This package, this repo, and this VPS have never held it.

## Restore procedure

1. Download `secrets.age`, `MANIFEST.json`, and `HASHES.json` from Drive.
2. Verify integrity before doing anything else:
   `sha256sum secrets.age MANIFEST.json RESTORE_INSTRUCTIONS.md` and compare
   against the values in `HASHES.json`. Do not proceed on a mismatch.
3. Decrypt: `age -d -i /path/to/your-private-key.txt secrets.age > secrets.decrypted`
4. `secrets.decrypted` now contains the labeled contents of each original
   `.env` file (`# === <filename> ===` sections). Split and place each
   section back at `/etc/nizam/<filename>` (root:root, mode 600) on the
   replacement VPS.
5. Cross-check `MANIFEST.json.env_file_variable_names` against what you just
   restored — the variable NAMES must match exactly; if they don't, a
   secret file was added or removed since this snapshot was taken and you
   need a newer package.
6. Delete `secrets.decrypted` once the values are back in `/etc/nizam/`.
   Never leave a decrypted copy on disk longer than the restore itself.

## What this package deliberately does NOT contain

- Any age private/decryption key.
- Any secret value in plaintext (only inside the encrypted `secrets.age`).
- Any hostname, IP address, or other deployment particular.
"""
